name: Update Recommend_sys

on:
  schedule:
    - cron: "0 0 * * *"  # 每天 0 點
  workflow_dispatch:

jobs:
  update-and-commit:
    runs-on: ubuntu-latest
    steps:
      # 1. 檢出程式碼
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. Python 3.9
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # 3. 下載 & 安裝 TA-Lib (C 原始碼)
      - name: Build & Install TA-Lib (C lib)
        run: |
          sudo apt-get update
          sudo apt-get install -y wget build-essential
          
          # 下載並解壓
          wget https://sourceforge.net/projects/ta-lib/files/ta-lib/0.4.0/ta-lib-0.4.0-src.tar.gz -O ta-lib-0.4.0-src.tar.gz
          tar -xzf ta-lib-0.4.0-src.tar.gz
          
          # 這裡的資料夾名稱應該是 `ta-lib-0.4.0`，非 `ta-lib-0.4.0-src`
          cd ta-lib-0.4.0
          
          ./configure --prefix=/usr/local
          make
          sudo make install
          cd ..
          rm -rf ta-lib-0.4.0 ta-lib-0.4.0-src.tar.gz
          
          # 更新 linker cache
          echo "/usr/local/lib" | sudo tee /etc/ld.so.conf.d/ta-lib.conf
          sudo ldconfig

      # 4. 安裝 Python 版 ta-lib & 其餘依賴
      - name: Install Python packages
        run: |
          # 升級 pip setuptools wheel
          python -m pip install --upgrade pip setuptools wheel
          
          # 安裝特定舊版 Numpy & Cython (供 ta-lib 編譯)
          pip install numpy==1.23.5 cython
          
          # 關鍵：--no-build-isolation 避免隔離環境拉到更高版 numpy
          pip install ta-lib --no-build-isolation --verbose
          
          # 安裝你專案中需要的其餘套件
          pip install -r requirements.txt
          
          # 確認能正常 import
          python -c "import talib; print('TA-Lib installation successful')"

      # 5. Pull 變更，避免衝突
      - name: Pull changes from remote
        run: git pull origin main

      # 6. 執行程式
      - name: Update data
        run: python recommend.py

      # 7. 若有變更就 commit & push
      - name: Commit and push if changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "drose01rrr@gmail.com"
          git config --global user.name "YIFUNLIN"
          git add -A
          git commit -m "Automated stock report update" -a || echo "No changes to commit"
          git push
