name: Update Recommend_sys
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget build-essential

      - name: Install TA-Lib
        run: |
          # 下載並安裝 TA-Lib
          wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
          tar -xzf ta-lib-0.4.0-src.tar.gz
          cd ta-lib/
          ./configure
          make
          sudo make install
          
          # 特別注意：複製庫文件到標準位置
          sudo cp /usr/local/lib/libta_lib.so.0 /usr/lib
          sudo cp /usr/local/lib/libta_lib.so.0.0.0 /usr/lib
          sudo cp /usr/local/lib/libta_lib.so /usr/lib
          sudo cp /usr/local/lib/libta_lib.la /usr/lib
          sudo cp /usr/local/lib/libta_lib.a /usr/lib
          
          # 更新庫緩存
          sudo ldconfig
          
          # 驗證安裝
          ls -l /usr/lib/libta_lib*
          
          cd ..
          rm -rf ta-lib ta-lib-0.4.0-src.tar.gz
          
      - name: Set TA-Lib environment variables
        run: |
          echo "LD_LIBRARY_PATH=/usr/lib:/usr/local/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install numpy==1.23.5
          # 使用 verbose 模式安裝 ta-lib 以獲得更多錯誤信息
          LIBRARY_PATH=/usr/lib C_INCLUDE_PATH=/usr/include pip install --verbose ta-lib
          pip install -r requirements.txt
          
      - name: Verify TA-Lib installation
        run: |
          python -c "import talib; print('TA-Lib installation successful')"
          
      - name: Pull changes from remote
        run: git pull origin main
        
      - name: Update data
        run: python recommend.py
        
      - name: Commit and push if changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "drose01rrr@gmail.com"
          git config --global user.name "YIFUNLIN"
          git add -A
          git commit -m "Automated stock report update" -a || echo "No changes to commit"
          git push
