name: Update Recommend_sys
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget build-essential

      - name: Install TA-Lib
        run: |
          # 下載並解壓 TA-Lib
          wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
          tar -xzf ta-lib-0.4.0-src.tar.gz
          cd ta-lib/
          ./configure --prefix=/usr
          make
          sudo make install
          cd ..
          # 確保系統能找到 TA-Lib 庫
          sudo ldconfig
          # 驗證安裝
          ls -l /usr/lib/libta_lib*
          
      - name: Set TA-Lib environment variables
        run: |
          echo "LD_LIBRARY_PATH=/usr/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "TA_LIBRARY_PATH=/usr/lib" >> $GITHUB_ENV
          echo "TA_INCLUDE_PATH=/usr/include" >> $GITHUB_ENV
          
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install numpy==1.23.5
          # 使用 verbose 模式安裝 ta-lib 以獲得更多錯誤信息
          pip install --verbose ta-lib
          pip install -r requirements.txt
          
      - name: Pull changes from remote
        run: git pull origin main
        
      - name: Update data
        run: python recommend.py
        
      - name: Commit and push if changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "drose01rrr@gmail.com"
          git config --global user.name "YIFUNLIN"
          git add -A
          git commit -m "Automated stock report update" -a || echo "No changes to commit"
          git push
