name: Update Recommend_sys
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  update-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget build-essential

      - name: Install TA-Lib
        run: |
          wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
          tar -xzf ta-lib-0.4.0-src.tar.gz
          cd ta-lib/
          ./configure
          make
          sudo make install
          cd ..
          
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install numpy==1.23.5
          pip install ta-lib
          pip install -r requirements.txt

      # 5. 從遠端拉取更改
      - name: Pull changes from remote
        run: git pull origin main

      # 6. 更新數據
      - name: Update data
        run: python recommend.py

      # 7. 如果有更改則提交
      - name: Commit and push if changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "drose01rrr@gmail.com"
          git config --global user.name "YIFUNLIN"
          git add -A
          git commit -m "Automated stock report update" -a || echo "No changes to commit"
          git push
