name: Update Data

on:
  schedule:
    # UTC 時間每天 0:00，即台灣時間早上 8:00
    - cron: "0 0 * * *"
  workflow_dispatch: # 允許手動觸發

jobs:
  update-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Pull changes from remote
        run: git pull origin main

      - name: Update data
        run: python recommend.py

      - name: Commit and push if changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "drose01rrr@gmail.com"
          git config --global user.name "YIFUNLIN"
          git add -A
          git commit -m "Automated stock report update" -a || echo "No changes to commit"
          git push
