name: Update Data

on:
  schedule:
    - cron: "0 22 * * *" # UTC 時間每天 22:00，即台灣時間早上 6:00
  workflow_dispatch: # 允許手動觸發
jobs:
  update-and-commit:
    runs-on: ubuntu-latest # 運行環境(runners)

    steps: # 官方的 GitHub Action配置
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Update data
        run: python update.py # 執行該腳本

      - name: Commit and push if changes # 完成資料更新後，腳本檢查是否有資料變更
        run: | # 如果有，將變更提交到 Git 倉庫並推送到 GitHub
          git config --global user.email "drose01rrr@gmail.com"
          git config --global user.name "YIFUNLIN"
          git add -A
          git commit -m "Automated data update" -a || echo "No changes to commit"
          git push
